### ISSUE TITLE
Locking errors running smashbox  test_shareGroup test

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud-archive/files_locking#30]
### Steps to reproduce
1. Install 8.1 
2. run smashbox test lib/oc-tests/test_shareGroup
3. Get locking error messages in log file
### Expected behaviour

Test should pass
### Actual behaviour

The test fails with these errors in the server log file:

```

{"reqId":"taVkknGV+0RpCvOH+H\/0","remoteAddr":"x.x.x.x","app":"PHP","message":"fopen(\/var\/www\/html\/owncloud\/data\/user3): failed to open stream: Is a director
y at \/var\/www\/html\/owncloud\/apps\/files_locking\/lib\/lock.php#134","level":3,"time":"2015-05-08T18:17:37+00:00"}
{"reqId":"taVkknGV+0RpCvOH+H\/0","remoteAddr":"x.x.x.x","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Target file  is locked by another proce
ss.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1087): OC\\\\Connector\\\\Sabre\\\\File->put(
Resource id #30)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(501): Sabre\\\\DAV\\\\Server->updateFile('TEST_FILE
_MODIF...', Resource id #30, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html
\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/ownc
loud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Respon
se))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/re
mote.php(84): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file
.php\",\"Line\":174}","level":4,"time":"2015-05-08T18:17:37+00:00"}


```
### Server Host info:

Ubuntu 14.04
PHP 5.5.9
### Server configuration:

ownCloud Enterprise Edition 8.1 alpha 3 (daily) Build:2015-05-07T03:08:39+00:00 55eaa165f8cd98aebc457fcfbd98c7a7c40f3e30

**Comment by DeepDiver1975** [comment]
the fix is available in beta1 - not alpha3 -> close as invalid

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/files_locking/commit/8739b42cdbfd3454afd5d9d2df549d443ba27f62

**Comment by DeepDiver1975** [comment]
![bildschirmfoto von 2015-05-08 21 09 21](https://cloud.githubusercontent.com/assets/1005065/7543660/877be74a-f5c6-11e4-813a-f6aa7ca5566d.png)
